[package]
name = "ppmtrans"
version = "0.1.0"
edition = "2021"

[dependencies]
array2 = { path = "../array2" }
clap = { version = "4.5.31", features = ["derive"] }
csc411_image = "0.5.2"
rayon = "1.10"
